#!/usr/bin/env pythong
"""Programming languages catalog — paradigms, typing, memory, compilation, Hostess relevance."""
from __future__ import annotations

LANG_ENTRIES: tuple[dict, ...] = (
    {"id": "c", "name": "C", "year": 1972, "paradigm": "imperative", "typing": "static weak",
     "memory": "manual", "tags": ("c", "systems", "pointer", "ansi c"),
     "body": "C: low-level systems language — functions, structs, pointers, manual memory. AMOURANTHRTX native engine, libx86emu, FieldStorage. stdint.h fixed-width types. Undefined behavior on overflow/aliasing — Hostess cites ISO C semantics."},
    {"id": "cpp", "name": "C++", "year": 1985, "paradigm": "multi-paradigm", "typing": "static strong",
     "memory": "manual+RAII", "tags": ("c++", "oop", "templates", "stl", "cxx20"),
     "body": "C++: RAII, templates, STL, OOP, constexpr, coroutines (C++20). AMOURANTHRTX Navigator/engine, Vulkan pipeline, FieldChips dies. Rule of zero/five, move semantics, noexcept for hot paths."},
    {"id": "rust", "name": "Rust", "year": 2010, "paradigm": "multi-paradigm", "typing": "static strong",
     "memory": "ownership", "tags": ("rust", "borrow checker", "cargo", "unsafe"),
     "body": "Rust: ownership, borrowing, lifetimes — compile-time memory safety without GC. unsafe for FFI. Cargo ecosystem. Ideal mental model for Hostess systems advice alongside C++ Field code."},
    {"id": "python", "name": "Python", "year": 1991, "paradigm": "multi-paradigm", "typing": "dynamic gradual",
     "memory": "gc", "tags": ("python", "scripting", "hostess", "brain"),
     "body": "Python 3: Hostess 7 brain scripts — field_superintelligence.py, corpora, QA gates. Dynamic typing, GIL, asyncio optional. dataclasses, pathlib, json for lossless brain shards."},
    {"id": "javascript", "name": "JavaScript", "year": 1995, "paradigm": "multi-paradigm", "typing": "dynamic weak",
     "memory": "gc", "tags": ("javascript", "ecmascript", "web", "node"),
     "body": "JavaScript (ECMAScript): event loop, prototypal inheritance, async/await, closures. Runs in browsers and Node. Type coercion pitfalls — === vs ==."},
    {"id": "typescript", "name": "TypeScript", "year": 2012, "paradigm": "multi-paradigm", "typing": "static structural",
     "memory": "gc", "tags": ("typescript", "ecmascript", "types"),
     "body": "TypeScript: structural types over JavaScript — interfaces, unions, generics, strict null checks. Compiles to JS; erases at runtime."},
    {"id": "java", "name": "Java", "year": 1995, "paradigm": "oop", "typing": "static strong",
     "memory": "gc", "tags": ("java", "jvm", "bytecode"),
     "body": "Java: JVM bytecode, classes, interfaces, garbage collection, generics erasure. Write once run anywhere — HotSpot JIT."},
    {"id": "kotlin", "name": "Kotlin", "year": 2011, "paradigm": "multi-paradigm", "typing": "static strong",
     "memory": "gc", "tags": ("kotlin", "jvm", "android"),
     "body": "Kotlin: null safety, coroutines, JVM/Native/JS targets. Interops with Java."},
    {"id": "swift", "name": "Swift", "year": 2014, "paradigm": "multi-paradigm", "typing": "static strong",
     "memory": "arc", "tags": ("swift", "apple", "arc"),
     "body": "Swift: ARC memory management, optionals, protocols, value semantics. Apple platforms primary target."},
    {"id": "go", "name": "Go", "year": 2009, "paradigm": "imperative concurrent", "typing": "static strong",
     "memory": "gc", "tags": ("go", "golang", "goroutine"),
     "body": "Go: goroutines, channels, simple syntax, fast compile, GC. Interfaces implicit satisfaction."},
    {"id": "zig", "name": "Zig", "year": 2016, "paradigm": "imperative", "typing": "static strong",
     "memory": "manual comptime", "tags": ("zig", "systems", "comptime"),
     "body": "Zig: no hidden control flow, comptime, C interop, optional allocator parameter. Error unions not exceptions."},
    {"id": "haskell", "name": "Haskell", "year": 1990, "paradigm": "functional pure", "typing": "static strong inferred",
     "memory": "gc lazy", "tags": ("haskell", "functional", "monad"),
     "body": "Haskell: pure functions, lazy evaluation, monads, type classes, GHC. Referential transparency."},
    {"id": "ocaml", "name": "OCaml", "year": 1996, "paradigm": "functional+imperative", "typing": "static strong inferred",
     "memory": "gc", "tags": ("ocaml", "ml", "functional"),
     "body": "OCaml: algebraic types, pattern matching, modules/functors, native and bytecode backends."},
    {"id": "fsharp", "name": "F#", "year": 2005, "paradigm": "functional", "typing": "static strong inferred",
     "memory": "gc", "tags": ("f#", "dotnet", "functional"),
     "body": "F#: .NET functional language — records, discriminated unions, pipelines, async workflows."},
    {"id": "lisp", "name": "Common Lisp", "year": 1984, "paradigm": "multi-paradigm", "typing": "dynamic strong",
     "memory": "gc", "tags": ("lisp", "s-expression", "macro"),
     "body": "Common Lisp: code-as-data macros, CLOS object system, REPL-driven development, conditions/restarts."},
    {"id": "scheme", "name": "Scheme", "year": 1975, "paradigm": "functional", "typing": "dynamic strong",
     "memory": "gc", "tags": ("scheme", "lisp", "r5rs", "r7rs"),
     "body": "Scheme: minimal Lisp — tail-call optimization, continuations, hygienic macros (R5RS/R7RS)."},
    {"id": "clojure", "name": "Clojure", "year": 2007, "paradigm": "functional", "typing": "dynamic strong",
     "memory": "gc immutable", "tags": ("clojure", "jvm", "lisp"),
     "body": "Clojure: immutable persistent data structures on JVM, STM, software transactional memory."},
    {"id": "erlang", "name": "Erlang", "year": 1986, "paradigm": "concurrent functional", "typing": "dynamic strong",
     "memory": "gc per-process", "tags": ("erlang", "otp", "actor"),
     "body": "Erlang/OTP: actor model, fault tolerance, hot code reload, telecom-grade distribution."},
    {"id": "elixir", "name": "Elixir", "year": 2011, "paradigm": "concurrent functional", "typing": "dynamic strong",
     "memory": "gc", "tags": ("elixir", "beam", "phoenix"),
     "body": "Elixir: runs on BEAM (Erlang VM), metaprogramming, Phoenix web, pipe operator."},
    {"id": "ruby", "name": "Ruby", "year": 1995, "paradigm": "oop dynamic", "typing": "dynamic strong duck",
     "memory": "gc", "tags": ("ruby", "rails", "matz"),
     "body": "Ruby: everything object, blocks, mixins, Rails ecosystem. MRI vs JRuby implementations."},
    {"id": "php", "name": "PHP", "year": 1995, "paradigm": "imperative", "typing": "dynamic weak gradual",
     "memory": "gc", "tags": ("php", "web", "server"),
     "body": "PHP: server-side web, request lifecycle, namespaces (PHP 5.3+), typed properties (7.4+)."},
    {"id": "perl", "name": "Perl", "year": 1987, "paradigm": "multi-paradigm", "typing": "dynamic weak",
     "memory": "gc", "tags": ("perl", "regex", "cpan"),
     "body": "Perl: regex-native, TIMTOWTDI, CPAN. Perl 5 vs Raku divergence."},
    {"id": "lua", "name": "Lua", "year": 1993, "paradigm": "multi-paradigm", "typing": "dynamic strong",
     "memory": "gc", "tags": ("lua", "embed", "game scripting"),
     "body": "Lua: lightweight embeddable scripting — tables, metatables, coroutines. Used in games/emulators."},
    {"id": "r", "name": "R", "year": 1993, "paradigm": "functional statistical", "typing": "dynamic",
     "memory": "gc", "tags": ("r", "statistics", "data science"),
     "body": "R: statistical computing, vectors/factors/data.frames, CRAN, ggplot2."},
    {"id": "fortran", "name": "Fortran", "year": 1957, "paradigm": "imperative scientific", "typing": "static strong",
     "memory": "manual", "tags": ("fortran", "hpc", "numerical"),
     "body": "Fortran: column-major arrays, numerical HPC heritage, DO loops, modern coarrays."},
    {"id": "cobol", "name": "COBOL", "year": 1959, "paradigm": "imperative business", "typing": "weak static",
     "memory": "manual", "tags": ("cobol", "mainframe", "business"),
     "body": "COBOL: PICTURE clauses, fixed decimal, verbose business records — still runs critical finance systems."},
    {"id": "pascal", "name": "Pascal", "year": 1970, "paradigm": "imperative", "typing": "static strong",
     "memory": "manual", "tags": ("pascal", "delphi", "teaching"),
     "body": "Pascal: structured programming teaching language — strong typing, nested procedures. Delphi/Object Pascal OOP extension."},
    {"id": "ada", "name": "Ada", "year": 1980, "paradigm": "imperative", "typing": "static strong",
     "memory": "manual", "tags": ("ada", "safety critical", "spark"),
     "body": "Ada: safety-critical systems — strong typing, tasks, protected objects, SPARK subset for formal proof."},
    {"id": "d", "name": "D", "year": 2001, "paradigm": "multi-paradigm", "typing": "static strong",
     "memory": "gc optional", "tags": ("d", "systems", "metaprogramming"),
     "body": "D: C++ successor ambitions — CTFE, ranges, @safe/@system, optional GC."},
    {"id": "nim", "name": "Nim", "year": 2008, "paradigm": "multi-paradigm", "typing": "static strong inferred",
     "memory": "manual optional gc", "tags": ("nim", "metaprogramming", "python-like"),
     "body": "Nim: Python-like syntax, compiles to C/C++/JS, powerful macro system."},
    {"id": "assembly", "name": "Assembly (generic)", "year": 1947, "paradigm": "imperative machine", "typing": "untyped",
     "memory": "manual", "tags": ("assembly", "asm", "mnemonic", "opcode"),
     "body": "Assembly: human-readable machine code — mnemonics map to opcodes per ISA. AMOURANTHRTX: AMMOASM (MASM subset), FieldChip6502/Z80/M68K/MIPS dies. One ISA per chip — see code brain infinite drive."},
    {"id": "ammoasm", "name": "AMMOASM", "year": 2025, "paradigm": "imperative", "typing": "untyped",
     "memory": "manual", "tags": ("ammoasm", "masm", "x86", "field", "ammocode"),
     "body": "AMMOASM v4 — FieldAmmoAsm.hpp MASM subset: MOV ADD INT JMP CALL RET CMP JE JNE PUBLIC EXTRN. Emits FieldAmmoObj objects for AMMORUN linker. DOS/Field RTX toolchain."},
    {"id": "sql", "name": "SQL", "year": 1974, "paradigm": "declarative", "typing": "static schema",
     "memory": "n/a", "tags": ("sql", "database", "relational"),
     "body": "SQL: relational algebra — SELECT FROM WHERE JOIN GROUP BY. Declarative query language; implementations: PostgreSQL, SQLite, MySQL."},
    {"id": "html", "name": "HTML", "year": 1991, "paradigm": "markup", "typing": "schema",
     "memory": "n/a", "tags": ("html", "web", "markup"),
     "body": "HTML: document structure markup — semantic elements, forms, accessibility. Not Turing-complete alone."},
    {"id": "css", "name": "CSS", "year": 1996, "paradigm": "declarative", "typing": "n/a",
     "memory": "n/a", "tags": ("css", "style", "web"),
     "body": "CSS: cascade, specificity, flexbox, grid, custom properties. Styles HTML presentation."},
    {"id": "shell", "name": "Bourne Shell / Bash", "year": 1979, "paradigm": "imperative glue", "typing": "untyped",
     "memory": "n/a", "tags": ("bash", "shell", "linux", "hostess7.sh"),
     "body": "Shell scripting: Hostess7.sh, linux.sh release gates — pipelines, env vars, case statements. AMOURANTHRTX orchestration layer."},
    {"id": "powershell", "name": "PowerShell", "year": 2006, "paradigm": "imperative object pipeline", "typing": "dynamic",
     "memory": "gc", "tags": ("powershell", "windows", "cmdlet"),
     "body": "PowerShell: .NET object pipelines, cmdlets, remoting — Windows automation."},
    {"id": "wasm", "name": "WebAssembly", "year": 2017, "paradigm": "stack machine", "typing": "static",
     "memory": "linear memory", "tags": ("wasm", "web", "portable"),
     "body": "WebAssembly: stack machine bytecode — near-native speed in browsers. WASI for system interfaces."},
    {"id": "cuda", "name": "CUDA C/C++", "year": 2007, "paradigm": "data parallel", "typing": "static",
     "memory": "manual gpu", "tags": ("cuda", "nvidia", "gpu", "kernel"),
     "body": "CUDA: SPMD kernels, thread blocks, shared memory, warp semantics — NVIDIA GPU compute."},
    {"id": "glsl", "name": "GLSL", "year": 2004, "paradigm": "data parallel", "typing": "static",
     "memory": "gpu", "tags": ("glsl", "shader", "opengl", "vulkan glsl"),
     "body": "GLSL: OpenGL shading language — vertex/fragment/compute stages. Vulkan uses SPIR-V (cross-compile from GLSL)."},
    {"id": "hlsl", "name": "HLSL", "year": 2002, "paradigm": "data parallel", "typing": "static",
     "memory": "gpu", "tags": ("hlsl", "directx", "shader"),
     "body": "HLSL: DirectX shader language — SM 6.x, ray tracing, mesh shaders."},
    {"id": "spirv", "name": "SPIR-V", "year": 2015, "paradigm": "ssa gpu ir", "typing": "static",
     "memory": "gpu", "tags": ("spirv", "vulkan", "shader ir"),
     "body": "SPIR-V: Khronos binary shader IR for Vulkan/OpenCL — AMOURANTHRTX Field die GPU path."},
    {"id": "vhdl", "name": "VHDL", "year": 1980, "paradigm": "hardware description", "typing": "strong",
     "memory": "n/a", "tags": ("vhdl", "fpga", "hdl"),
     "body": "VHDL: IEEE hardware description — signals, processes, synthesis to FPGA/ASIC."},
    {"id": "verilog", "name": "Verilog", "year": 1984, "paradigm": "hardware description", "typing": "weak",
     "memory": "n/a", "tags": ("verilog", "systemverilog", "hdl"),
     "body": "Verilog/SystemVerilog: RTL design, simulation, assertions — dominant ASIC/FPGA flow."},
    {"id": "matlab", "name": "MATLAB", "year": 1984, "paradigm": "numerical matrix", "typing": "dynamic",
     "memory": "gc", "tags": ("matlab", "matrix", "simulink"),
     "body": "MATLAB: matrix-first numerical computing, toolboxes, Simulink model-based design."},
    {"id": "julia", "name": "Julia", "year": 2012, "paradigm": "multi-paradigm scientific", "typing": "dynamic optional static",
     "memory": "gc", "tags": ("julia", "scientific", "multiple dispatch"),
     "body": "Julia: multiple dispatch, JIT to LLVM, scientific computing performance."},
    {"id": "solidity", "name": "Solidity", "year": 2014, "paradigm": "contract imperative", "typing": "static",
     "memory": "evm", "tags": ("solidity", "ethereum", "smart contract"),
     "body": "Solidity: EVM smart contracts — gas costs, reentrancy risks, compiler versions matter."},
    {"id": "prolog", "name": "Prolog", "year": 1972, "paradigm": "logic", "typing": "dynamic",
     "memory": "gc", "tags": ("prolog", "logic", "unification"),
     "body": "Prolog: Horn clauses, unification, backtracking — logic programming paradigm."},
    {"id": "smalltalk", "name": "Smalltalk", "year": 1972, "paradigm": "pure oop", "typing": "dynamic strong",
     "memory": "gc", "tags": ("smalltalk", "oop", "message passing"),
     "body": "Smalltalk: everything is object, message passing, live image — influenced Java/C# UI patterns."},
    {"id": "vba", "name": "VBA", "year": 1993, "paradigm": "imperative", "typing": "dynamic weak",
     "memory": "gc", "tags": ("vba", "excel", "office"),
     "body": "VBA: Office automation — macros in Excel/Word; security sandbox considerations."},
    {"id": "objective_c", "name": "Objective-C", "year": 1984, "paradigm": "oop", "typing": "dynamic weak",
     "memory": "arc/manual", "tags": ("objective-c", "objc", "apple legacy"),
     "body": "Objective-C: Smalltalk messaging on C — brackets, NSObject, legacy Apple/macOS codebases."},
    {"id": "dart", "name": "Dart", "year": 2011, "paradigm": "oop", "typing": "static strong",
     "memory": "gc", "tags": ("dart", "flutter", "vm"),
     "body": "Dart: Flutter UI framework language — sound null safety, AOT/JIT compilation."},
    {"id": "scala", "name": "Scala", "year": 2004, "paradigm": "functional+oop", "typing": "static strong",
     "memory": "gc", "tags": ("scala", "jvm", "functional"),
     "body": "Scala: JVM language — case classes, pattern matching, implicits, Akka actors."},
    {"id": "groovy", "name": "Groovy", "year": 2003, "paradigm": "dynamic jvm", "typing": "dynamic optional static",
     "memory": "gc", "tags": ("groovy", "jvm", "gradle"),
     "body": "Groovy: Java-syntax-compatible dynamic JVM language — Gradle build scripts."},
    {"id": "tcl", "name": "Tcl", "year": 1988, "paradigm": "imperative embed", "typing": "dynamic",
     "memory": "gc", "tags": ("tcl", "tk", "embed"),
     "body": "Tcl/Tk: embeddable scripting + GUI toolkit — everything is a string early design."},
    {"id": "forth", "name": "Forth", "year": 1970, "paradigm": "stack", "typing": "untyped",
     "memory": "manual", "tags": ("forth", "stack", "boot"),
     "body": "Forth: postfix stack language — extensible via defining words; boot firmware tradition."},
    {"id": "apl", "name": "APL", "year": 1966, "paradigm": "array functional", "typing": "dynamic",
     "memory": "gc", "tags": ("apl", "array", "symbols"),
     "body": "APL: array-oriented — special symbols, tacit programming, dense mathematical notation."},
    {"id": "mathematica", "name": "Wolfram Language", "year": 1988, "paradigm": "symbolic multi-paradigm", "typing": "dynamic",
     "memory": "gc", "tags": ("mathematica", "wolfram", "symbolic"),
     "body": "Wolfram Language: symbolic computation, notebooks, built-in knowledge — Mathematica kernel."},
    {"id": "json", "name": "JSON", "year": 2001, "paradigm": "data interchange", "typing": "schema optional",
     "memory": "n/a", "tags": ("json", "data", "brain", "lossless"),
     "body": "JSON: lossless data interchange — Hostess brain corpora, protocol_v33.json, infinite drive shards."},
    {"id": "yaml", "name": "YAML", "year": 2001, "paradigm": "data serialization", "typing": "schema optional",
     "memory": "n/a", "tags": ("yaml", "config", "devops"),
     "body": "YAML: human-readable config — anchors, merges; security caution on arbitrary object deserialization."},
    {"id": "regex", "name": "Regular Expressions", "year": 1951, "paradigm": "declarative pattern", "typing": "n/a",
     "memory": "n/a", "tags": ("regex", "pattern", "parsing"),
     "body": "Regular expressions: formal language subset — NFA/DFA, PCRE extensions, used in Hostess intent routing."},
    {"id": "markdown", "name": "Markdown", "year": 2004, "paradigm": "markup lightweight", "typing": "n/a",
     "memory": "n/a", "tags": ("markdown", "md", "docs"),
     "body": "Markdown: lightweight markup — CommonMark/GFM variants for docs and README."},
    {"id": "graphql", "name": "GraphQL", "year": 2015, "paradigm": "query api", "typing": "schema",
     "memory": "n/a", "tags": ("graphql", "api", "query"),
     "body": "GraphQL: client-specified queries over typed schema — introspection, N+1 resolver caution."},
    {"id": "protobuf", "name": "Protocol Buffers", "year": 2008, "paradigm": "serialization idl", "typing": "schema",
     "memory": "n/a", "tags": ("protobuf", "grpc", "serialization"),
     "body": "Protobuf: binary IDL serialization — gRPC services, backward-compatible field evolution."},
    {"id": "linux", "name": "Linux (Field substrate)", "year": 1991, "paradigm": "POSIX kernel + userspace", "typing": "dynamic",
     "memory": "virtual memory + cgroups", "tags": ("linux", "posix", "systemd", "kernel", "glibc", "hostess7.sh"),
     "body": "Linux on Field: incumbent substrate runs as guest under KILROY Field Die — HostPassthrough glibc, unmodified binaries. "
              "systemd/nftables/polkit/tristate installer path. Hostess7.sh and install-all.sh orchestrate the stack; "
              "/proc/kilroy_field witnesses syscall truth. Shell, apt, cgroups, namespaces map to combinatronic ops."},
    {"id": "economics", "name": "Economics (Master Economist)", "year": 1776, "paradigm": "social science quantitative", "typing": "model-based",
     "memory": "n/a", "tags": ("economics", "macro", "micro", "finance", "trade", "openstax", "master economist"),
     "body": "Hostess 7 Master Economist — macro (GDP, inflation, policy), micro (supply/demand, elasticity), "
              "finance (risk, portfolio), trade (tariffs, supply chains), business (CAC/LTV, unit economics), "
              "and field_economics (sovereign compute, bandwidth, defense cost). Truth-gated: 94% noise discarded."},
)


def iter_lang_entries() -> list[dict]:
    rows: list[dict] = []
    for e in LANG_ENTRIES:
        rows.append({
            "id": f"lang_{e['id']}",
            "name": e["name"],
            "full_name": e["name"],
            "year": e.get("year"),
            "paradigm": e.get("paradigm", ""),
            "typing": e.get("typing", ""),
            "memory": e.get("memory", ""),
            "category": "programming_language",
            "body": e["body"],
            "tags": tuple(e.get("tags") or ()),
        })
    return rows


def lang_count() -> int:
    return len(LANG_ENTRIES)