# Portable Grok16 toolchain — env GROK16_ROOT or relative from Queen/cmake
if(DEFINED ENV{GROK16_ROOT})
  set(_GROK16_PREFIX "$ENV{GROK16_ROOT}")
else()
  get_filename_component(_GROK16_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../../Grok16" ABSOLUTE)
endif()
set(_G16_DRIVER "${_GROK16_PREFIX}/bin/g16")
set(CMAKE_C_COMPILER "${_G16_DRIVER}" CACHE FILEPATH "Grok16 g16 (C mode)" FORCE)
set(CMAKE_CXX_COMPILER "${_G16_DRIVER}" CACHE FILEPATH "Grok16 g16 (C++ mode)" FORCE)
unset(_G16_DRIVER)
set(WRDT_G16_VERSION "16.1.1" CACHE STRING "G16 version" FORCE)
set(GROK16_PREFIX "${_GROK16_PREFIX}" CACHE PATH "Grok16 install prefix" FORCE)
set(GROK16_CXX_STD "gnu++26" CACHE STRING "Grok16 default C++ standard" FORCE)
set(GROK16_C_STD "gnu17" CACHE STRING "Grok16 default C standard" FORCE)
unset(_GROK16_PREFIX)