# Queen inside preset — delegates to Grok16 field cmake (canonical).
if(DEFINED ENV{GROK16_ROOT} AND NOT "$ENV{GROK16_ROOT}" STREQUAL "")
  set(_GROK16_ROOT "$ENV{GROK16_ROOT}")
else()
  get_filename_component(_GROK16_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../Grok16" ABSOLUTE)
endif()
if(EXISTS "${_GROK16_ROOT}/cmake/grok16-field-queen-rtx.cmake")
  include("${_GROK16_ROOT}/cmake/grok16-field-queen-rtx.cmake")
else()
  set(QUEEN_BROWSER_BUILD ON CACHE BOOL "Queen single RTX exe" FORCE)
  set(QUEEN_DEPS_INSIDE ON CACHE BOOL "Use Queen/vendor/deps" FORCE)
  set(QUEEN_USE_SYSTEM_SDL3 OFF CACHE BOOL "Vendored SDL3 inside Queen" FORCE)
  set(FETCH_SDL3 OFF CACHE BOOL "" FORCE)
  set(FETCH_SDL3_IMAGE OFF CACHE BOOL "" FORCE)
  set(FETCH_SDL3_MIXER OFF CACHE BOOL "" FORCE)
  set(FETCH_SDL3_TTF OFF CACHE BOOL "" FORCE)
  set(ENABLE_VALIDATION OFF CACHE BOOL "" FORCE)
  set(FIELD_DOS_EMBED_HD OFF CACHE BOOL "" FORCE)
  set(QUEEN_MINIMAL_BUILD ON CACHE BOOL "Skip host QA binaries" FORCE)
  set(CMAKE_BUILD_TYPE Release CACHE STRING "Queen RTX optimized build" FORCE)
endif()
unset(_GROK16_ROOT)