/* AmmoOS Image — field research rewrite (G16 field_opt).
 * RTX-gated paths: see GIMP-Field/data/rtx-gated-content.json
 * OS brand: AmmoOS · product: AmmoOS Image 1.0
 */
/* AmmoOS Image - The AmmoOS Field Image Research
 * Copyright (C) 1995 Spencer Kimball and Peter Mattis
 *
 * gimphelp-ids.h
 * Copyright (C) 2003 Michael Natterer <mitch@ammoos.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once


#define GIMP_HELP_MAIN                            "ammoos-main"

#define GIMP_HELP_FILE_NEW                        "ammoos-file-new"
#define GIMP_HELP_FILE_OPEN                       "ammoos-file-open"
#define GIMP_HELP_FILE_OPEN_AS_LAYER              "ammoos-file-open-as-layer"
#define GIMP_HELP_FILE_OPEN_AS_LINK_LAYER         "ammoos-file-open-as-link-layer"
#define GIMP_HELP_FILE_OPEN_LOCATION              "ammoos-file-open-location"
#define GIMP_HELP_FILE_OPEN_BY_EXTENSION          "ammoos-file-open-by-extension"
#define GIMP_HELP_FILE_OPEN_RECENT                "ammoos-file-open-recent"
#define GIMP_HELP_FILE_SAVE                       "ammoos-file-save"
#define GIMP_HELP_FILE_SAVE_AS                    "ammoos-file-save-as"
#define GIMP_HELP_FILE_SAVE_A_COPY                "ammoos-file-save-a-copy"
#define GIMP_HELP_FILE_SAVE_BY_EXTENSION          "ammoos-file-save-by-extension"
#define GIMP_HELP_FILE_EXPORT                     "ammoos-file-export"
#define GIMP_HELP_FILE_EXPORT_AS                  "ammoos-file-export-as"
#define GIMP_HELP_FILE_OVERWRITE                  "ammoos-file-overwrite"
#define GIMP_HELP_FILE_REVERT                     "ammoos-file-revert"
#define GIMP_HELP_FILE_CLOSE                      "ammoos-file-close"
#define GIMP_HELP_FILE_CLOSE_ALL                  "ammoos-file-close-all"
#define GIMP_HELP_FILE_COPY_LOCATION              "ammoos-file-copy-location"
#define GIMP_HELP_FILE_SHOW_IN_FILE_MANAGER       "ammoos-file-show-in-file-manager"
#define GIMP_HELP_FILE_CREATE_TEMPLATE            "ammoos-file-create-template"
#define GIMP_HELP_FILE_QUIT                       "ammoos-file-quit"

#define GIMP_HELP_EDIT_UNDO                       "ammoos-edit-undo"
#define GIMP_HELP_EDIT_REDO                       "ammoos-edit-redo"
#define GIMP_HELP_EDIT_STRONG_UNDO                "ammoos-edit-strong-undo"
#define GIMP_HELP_EDIT_STRONG_REDO                "ammoos-edit-strong-redo"
#define GIMP_HELP_EDIT_UNDO_CLEAR                 "ammoos-edit-undo-clear"
#define GIMP_HELP_EDIT_CUT                        "ammoos-edit-cut"
#define GIMP_HELP_EDIT_COPY                       "ammoos-edit-copy"
#define GIMP_HELP_EDIT_COPY_VISIBLE               "ammoos-edit-copy-visible"
#define GIMP_HELP_EDIT_PASTE                      "ammoos-edit-paste"
#define GIMP_HELP_EDIT_PASTE_IN_PLACE             "ammoos-edit-paste-in-place"
#define GIMP_HELP_EDIT_PASTE_INTO                 "ammoos-edit-paste-into"
#define GIMP_HELP_EDIT_PASTE_INTO_IN_PLACE        "ammoos-edit-paste-into-in-place"
#define GIMP_HELP_EDIT_PASTE_AS_NEW_LAYER         "ammoos-edit-paste-as-new-layer"
#define GIMP_HELP_EDIT_PASTE_AS_NEW_LAYER_IN_PLACE "ammoos-edit-paste-as-new-layer-in-place"
#define GIMP_HELP_EDIT_PASTE_AS_NEW_IMAGE         "ammoos-edit-paste-as-new-image"
#define GIMP_HELP_EDIT_PASTE_FLOAT                "ammoos-edit-paste-float"
#define GIMP_HELP_EDIT_PASTE_FLOAT_IN_PLACE       "ammoos-edit-paste-float-in-place"
#define GIMP_HELP_EDIT_CLEAR                      "ammoos-edit-clear"
#define GIMP_HELP_EDIT_FILL_FG                    "ammoos-edit-fill-fg"
#define GIMP_HELP_EDIT_FILL_BG                    "ammoos-edit-fill-bg"
#define GIMP_HELP_EDIT_FILL_PATTERN               "ammoos-edit-fill-pattern"

#define GIMP_HELP_SELECTION_DIALOG                "ammoos-selection-dialog"
#define GIMP_HELP_SELECTION_ALL                   "ammoos-selection-all"
#define GIMP_HELP_SELECTION_NONE                  "ammoos-selection-none"
#define GIMP_HELP_SELECTION_INVERT                "ammoos-selection-invert"
#define GIMP_HELP_SELECTION_FLOAT                 "ammoos-selection-float"
#define GIMP_HELP_SELECTION_FEATHER               "ammoos-selection-feather"
#define GIMP_HELP_SELECTION_SHARPEN               "ammoos-selection-sharpen"
#define GIMP_HELP_SELECTION_SHRINK                "ammoos-selection-shrink"
#define GIMP_HELP_SELECTION_GROW                  "ammoos-selection-grow"
#define GIMP_HELP_SELECTION_BORDER                "ammoos-selection-border"
#define GIMP_HELP_SELECTION_FLOOD                 "ammoos-selection-flood"
#define GIMP_HELP_SELECTION_FILL                  "ammoos-selection-fill"
#define GIMP_HELP_SELECTION_STROKE                "ammoos-selection-stroke"
#define GIMP_HELP_SELECTION_TO_CHANNEL            "ammoos-selection-to-channel"
#define GIMP_HELP_SELECTION_TO_PATH               "ammoos-selection-to-path"

#define GIMP_HELP_VIEW_NEW                        "ammoos-view-new"
#define GIMP_HELP_VIEW_SHOW_ALL                   "ammoos-view-show-all"
#define GIMP_HELP_VIEW_DOT_FOR_DOT                "ammoos-view-dot-for-dot"
#define GIMP_HELP_VIEW_RESET                      "ammoos-view-reset"
#define GIMP_HELP_VIEW_SCROLL_CENTER              "ammoos-view-scroll-center"
#define GIMP_HELP_VIEW_ZOOM_REVERT                "ammoos-view-zoom-revert"
#define GIMP_HELP_VIEW_ZOOM_OUT                   "ammoos-view-zoom-out"
#define GIMP_HELP_VIEW_ZOOM_IN                    "ammoos-view-zoom-in"
#define GIMP_HELP_VIEW_ZOOM_100                   "ammoos-view-zoom-100"
#define GIMP_HELP_VIEW_ZOOM_FIT_IN                "ammoos-view-zoom-fit-in"
#define GIMP_HELP_VIEW_ZOOM_FILL                  "ammoos-view-zoom-fill"
#define GIMP_HELP_VIEW_ZOOM_SELECTION             "ammoos-view-zoom-selection"
#define GIMP_HELP_VIEW_ZOOM_OTHER                 "ammoos-view-zoom-other"
#define GIMP_HELP_VIEW_FLIP                       "ammoos-view-flip"
#define GIMP_HELP_VIEW_FLIP_RESET                 "ammoos-view-flip-reset"
#define GIMP_HELP_VIEW_ROTATE_RESET               "ammoos-view-rotate-reset"
#define GIMP_HELP_VIEW_ROTATE_15                  "ammoos-view-rotate-15"
#define GIMP_HELP_VIEW_ROTATE_90                  "ammoos-view-rotate-90"
#define GIMP_HELP_VIEW_ROTATE_180                 "ammoos-view-rotate-180"
#define GIMP_HELP_VIEW_ROTATE_270                 "ammoos-view-rotate-270"
#define GIMP_HELP_VIEW_ROTATE_345                 "ammoos-view-rotate-345"
#define GIMP_HELP_VIEW_ROTATE_OTHER               "ammoos-view-rotate-other"
#define GIMP_HELP_VIEW_COLOR_MANAGEMENT           "ammoos-view-color-management"
#define GIMP_HELP_VIEW_COLOR_MANAGE_VIEW          "ammoos-view-color-manage-view"
#define GIMP_HELP_VIEW_SOFT_PROOF_VIEW            "ammoos-view-soft-proof-view"
#define GIMP_HELP_VIEW_SOFT_PROOF_RENDERING_INTENT "ammoos-view-soft-proof-rendering-intent"
#define GIMP_HELP_VIEW_SOFT_PROOF_BLACK_POINT     "ammoos-view-soft-proof-black-point"
#define GIMP_HELP_VIEW_MARK_OUT_OF_GAMUT          "ammoos-view-soft-mark-out-of-gamut"
#define GIMP_HELP_VIEW_COLOR_MANAGEMENT_RESET     "ammoos-view-color-management-reset"
#define GIMP_HELP_VIEW_SHOW_SELECTION             "ammoos-view-show-selection"
#define GIMP_HELP_VIEW_SHOW_LAYER_BOUNDARY        "ammoos-view-show-layer-boundary"
#define GIMP_HELP_VIEW_SHOW_CANVAS_BOUNDARY       "ammoos-view-show-canvas-boundary"
#define GIMP_HELP_VIEW_SHOW_GUIDES                "ammoos-view-show-guides"
#define GIMP_HELP_VIEW_SHOW_GRID                  "ammoos-view-show-grid"
#define GIMP_HELP_VIEW_SHOW_SAMPLE_POINTS         "ammoos-view-show-sample-points"
#define GIMP_HELP_VIEW_SNAP_TO_GUIDES             "ammoos-view-snap-to-guides"
#define GIMP_HELP_VIEW_SNAP_TO_GRID               "ammoos-view-snap-to-grid"
#define GIMP_HELP_VIEW_SNAP_TO_CANVAS             "ammoos-view-snap-to-canvas"
#define GIMP_HELP_VIEW_SNAP_TO_PATH               "ammoos-view-snap-to-path"
#define GIMP_HELP_VIEW_SNAP_TO_BBOX               "ammoos-view-snap-to-bbox"
#define GIMP_HELP_VIEW_SNAP_TO_EQUIDISTANCE       "ammoos-view-snap-to-equidistance"
#define GIMP_HELP_VIEW_SHOW_MENUBAR               "ammoos-view-show-menubar"
#define GIMP_HELP_VIEW_SHOW_RULERS                "ammoos-view-show-rulers"
#define GIMP_HELP_VIEW_SHOW_SCROLLBARS            "ammoos-view-show-scrollbars"
#define GIMP_HELP_VIEW_SHOW_STATUSBAR             "ammoos-view-show-statusbar"
#define GIMP_HELP_VIEW_PADDING_COLOR              "ammoos-view-padding-color"
#define GIMP_HELP_VIEW_SHRINK_WRAP                "ammoos-view-shrink-wrap"
#define GIMP_HELP_VIEW_FULLSCREEN                 "ammoos-view-fullscreen"
#define GIMP_HELP_VIEW_CHANGE_SCREEN              "ammoos-view-change-screen"

#define GIMP_HELP_IMAGE_WINDOW                    "ammoos-image-window"
#define GIMP_HELP_IMAGE_WINDOW_ORIGIN             "ammoos-image-window-origin"
#define GIMP_HELP_IMAGE_WINDOW_ZOOM_FOLLOW_BUTTON "ammoos-image-window-zoom-follow-button"
#define GIMP_HELP_IMAGE_WINDOW_QUICK_MASK_BUTTON  "ammoos-image-window-quick-mask-button"
#define GIMP_HELP_IMAGE_WINDOW_NAV_BUTTON         "ammoos-image-window-nav-button"
#define GIMP_HELP_IMAGE_WINDOW_RULER              "ammoos-image-window-ruler"
#define GIMP_HELP_IMAGE_WINDOW_STATUS_BAR         "ammoos-image-window-status-bar"


#define GIMP_HELP_IMAGE_DIALOG                    "ammoos-image-dialog"
#define GIMP_HELP_IMAGE_DUPLICATE                 "ammoos-image-duplicate"
#define GIMP_HELP_IMAGE_CONVERT_RGB               "ammoos-image-convert-rgb"
#define GIMP_HELP_IMAGE_CONVERT_GRAYSCALE         "ammoos-image-convert-grayscale"
#define GIMP_HELP_IMAGE_CONVERT_INDEXED           "ammoos-image-convert-indexed"
#define GIMP_HELP_IMAGE_CONVERT_U8                "ammoos-image-convert-u8"
#define GIMP_HELP_IMAGE_CONVERT_U16               "ammoos-image-convert-u16"
#define GIMP_HELP_IMAGE_CONVERT_U32               "ammoos-image-convert-u32"
#define GIMP_HELP_IMAGE_CONVERT_HALF              "ammoos-image-convert-half"
#define GIMP_HELP_IMAGE_CONVERT_FLOAT             "ammoos-image-convert-float"
#define GIMP_HELP_IMAGE_CONVERT_DOUBLE            "ammoos-image-convert-double"
#define GIMP_HELP_IMAGE_CONVERT_GAMMA             "ammoos-image-convert-gamma"
#define GIMP_HELP_IMAGE_CONVERT_PRECISION         "ammoos-image-convert-precision"
#define GIMP_HELP_IMAGE_FLIP_HORIZONTAL           "ammoos-image-flip-horizontal"
#define GIMP_HELP_IMAGE_FLIP_VERTICAL             "ammoos-image-flip-vertical"
#define GIMP_HELP_IMAGE_ROTATE_90                 "ammoos-image-rotate-90"
#define GIMP_HELP_IMAGE_ROTATE_180                "ammoos-image-rotate-180"
#define GIMP_HELP_IMAGE_ROTATE_270                "ammoos-image-rotate-270"
#define GIMP_HELP_IMAGE_RESIZE                    "ammoos-image-resize"
#define GIMP_HELP_IMAGE_RESIZE_TO_LAYERS          "ammoos-image-resize-to-layers"
#define GIMP_HELP_IMAGE_RESIZE_TO_SELECTION       "ammoos-image-resize-to-selection"
#define GIMP_HELP_IMAGE_PRINT_SIZE                "ammoos-image-print-size"
#define GIMP_HELP_IMAGE_SCALE                     "ammoos-image-scale"
#define GIMP_HELP_IMAGE_SCALE_WARNING             "ammoos-image-scale-warning"
#define GIMP_HELP_IMAGE_CROP                      "ammoos-image-crop"
#define GIMP_HELP_IMAGE_MERGE_LAYERS              "ammoos-image-merge-layers"
#define GIMP_HELP_IMAGE_FLATTEN                   "ammoos-image-flatten"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_ASSIGN      "ammoos-image-color-profile-assign"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_CONVERT     "ammoos-image-color-profile-convert"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_DISCARD     "ammoos-image-color-profile-discard"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_USE_SRGB    "ammoos-image-color-profile-use-srgb"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_SAVE        "ammoos-image-color-profile-save"
#define GIMP_HELP_IMAGE_COLOR_PROFILE_IMPORT      "ammoos-image-color-profile-import"
#define GIMP_HELP_IMAGE_SOFT_PROOF_PROFILE_ASSIGN "ammoos-image-soft-proof-profile-assign"
#define GIMP_HELP_IMAGE_SOFT_PROOF_BLACK_POINT    "ammoos-image-soft-proof-black-point"
#define GIMP_HELP_IMAGE_SOFT_PROOF_RENDERING_INTENT "ammoos-image-soft-proof-rendering-intent"

#define GIMP_HELP_IMAGE_METADATA_ROTATION_IMPORT  "ammoos-image-metadata-rotation-import"
#define GIMP_HELP_IMAGE_GRID                      "ammoos-image-grid"
#define GIMP_HELP_IMAGE_PROPERTIES                "ammoos-image-properties"

#define GIMP_HELP_LAYER_DIALOG                    "ammoos-layer-dialog"
#define GIMP_HELP_LAYER_DIALOG_PAINT_MODE_MENU    "ammoos-layer-dialog-paint-mode-menu"
#define GIMP_HELP_LAYER_DIALOG_OPACITY_SCALE      "ammoos-layer-dialog-opacity-scale"

#define GIMP_HELP_LAYER_NEW                       "ammoos-layer-new"
#define GIMP_HELP_LAYER_NEW_FROM_VISIBLE          "ammoos-layer-new-from-visible"
#define GIMP_HELP_LAYER_DUPLICATE                 "ammoos-layer-duplicate"
#define GIMP_HELP_LAYER_ANCHOR                    "ammoos-layer-anchor"
#define GIMP_HELP_LAYER_MERGE_DOWN                "ammoos-layer-merge-down"
#define GIMP_HELP_LAYER_MERGE_GROUP               "ammoos-layer-merge-group"
#define GIMP_HELP_LAYER_DELETE                    "ammoos-layer-delete"
#define GIMP_HELP_LAYER_TEXT_DISCARD              "ammoos-layer-text-discard"
#define GIMP_HELP_LAYER_TEXT_TO_PATH              "ammoos-layer-text-to-path"
#define GIMP_HELP_LAYER_TEXT_ALONG_PATH           "ammoos-layer-text-along-path"
#define GIMP_HELP_LAYER_PREVIOUS                  "ammoos-layer-previous"
#define GIMP_HELP_LAYER_NEXT                      "ammoos-layer-next"
#define GIMP_HELP_LAYER_TOP                       "ammoos-layer-top"
#define GIMP_HELP_LAYER_BOTTOM                    "ammoos-layer-bottom"
#define GIMP_HELP_LAYER_RAISE                     "ammoos-layer-raise"
#define GIMP_HELP_LAYER_RAISE_TO_TOP              "ammoos-layer-raise-to-top"
#define GIMP_HELP_LAYER_LOWER                     "ammoos-layer-lower"
#define GIMP_HELP_LAYER_LOWER_TO_BOTTOM           "ammoos-layer-lower-to-bottom"
#define GIMP_HELP_LAYER_WHITE_BALANCE             "ammoos-layer-white-balance"
#define GIMP_HELP_LAYER_EQUALIZE                  "ammoos-layer-equalize"
#define GIMP_HELP_LAYER_VISIBLE                   "ammoos-layer-visible"
#define GIMP_HELP_LAYER_LINKED                    "ammoos-layer-linked"
#define GIMP_HELP_LAYER_COLOR_TAG                 "ammoos-layer-color-tag"
#define GIMP_HELP_LAYER_EFFECTS                   "ammoos-layer-effects"
#define GIMP_HELP_LAYER_OPACITY                   "ammoos-layer-opacity"
#define GIMP_HELP_LAYER_MODE                      "ammoos-layer-mode"
#define GIMP_HELP_LAYER_LOCK_ALPHA                "ammoos-layer-lock-alpha"
#define GIMP_HELP_LAYER_LOCK_PIXELS               "ammoos-layer-lock-pixels"
#define GIMP_HELP_LAYER_LOCK_POSITION             "ammoos-layer-lock-position"
#define GIMP_HELP_LAYER_LOCK_VISIBILITY           "ammoos-layer-lock-visibility"
#define GIMP_HELP_LAYER_MASK_ADD                  "ammoos-layer-mask-add"
#define GIMP_HELP_LAYER_MASK_APPLY                "ammoos-layer-mask-apply"
#define GIMP_HELP_LAYER_MASK_DELETE               "ammoos-layer-mask-delete"
#define GIMP_HELP_LAYER_MASK_EDIT                 "ammoos-layer-mask-edit"
#define GIMP_HELP_LAYER_MASK_SHOW                 "ammoos-layer-mask-show"
#define GIMP_HELP_LAYER_MASK_DISABLE              "ammoos-layer-mask-disable"
#define GIMP_HELP_LAYER_MASK_SELECTION_REPLACE    "ammoos-layer-mask-selection-replace"
#define GIMP_HELP_LAYER_MASK_SELECTION_ADD        "ammoos-layer-mask-selection-add"
#define GIMP_HELP_LAYER_MASK_SELECTION_SUBTRACT   "ammoos-layer-mask-selection-subtract"
#define GIMP_HELP_LAYER_MASK_SELECTION_INTERSECT  "ammoos-layer-mask-selection-intersect"
#define GIMP_HELP_LAYER_ALPHA_ADD                 "ammoos-layer-alpha-add"
#define GIMP_HELP_LAYER_ALPHA_REMOVE              "ammoos-layer-alpha-remove"
#define GIMP_HELP_LAYER_ALPHA_SELECTION_REPLACE   "ammoos-layer-alpha-selection-replace"
#define GIMP_HELP_LAYER_ALPHA_SELECTION_ADD       "ammoos-layer-alpha-selection-add"
#define GIMP_HELP_LAYER_ALPHA_SELECTION_SUBTRACT  "ammoos-layer-alpha-selection-subtract"
#define GIMP_HELP_LAYER_ALPHA_SELECTION_INTERSECT "ammoos-layer-alpha-selection-intersect"
#define GIMP_HELP_LAYER_FLIP_HORIZONTAL           "ammoos-layer-flip-horizontal"
#define GIMP_HELP_LAYER_FLIP_VERTICAL             "ammoos-layer-flip-vertical"
#define GIMP_HELP_LAYER_ROTATE_90                 "ammoos-layer-rotate-90"
#define GIMP_HELP_LAYER_ROTATE_180                "ammoos-layer-rotate-180"
#define GIMP_HELP_LAYER_ROTATE_270                "ammoos-layer-rotate-270"
#define GIMP_HELP_LAYER_RESIZE                    "ammoos-layer-resize"
#define GIMP_HELP_LAYER_RESIZE_TO_IMAGE           "ammoos-layer-resize-to-image"
#define GIMP_HELP_LAYER_SCALE                     "ammoos-layer-scale"
#define GIMP_HELP_LAYER_RESIZE_TO_SELECTION       "ammoos-layer-resize-to-selection"
#define GIMP_HELP_LAYER_CROP_TO_CONTENT           "ammoos-layer-crop-to-content"
#define GIMP_HELP_LAYER_EDIT                      "ammoos-layer-edit"

#define GIMP_HELP_CHANNEL_DIALOG                  "ammoos-channel-dialog"
#define GIMP_HELP_CHANNEL_NEW                     "ammoos-channel-new"
#define GIMP_HELP_CHANNEL_RAISE                   "ammoos-channel-raise"
#define GIMP_HELP_CHANNEL_RAISE_TO_TOP            "ammoos-channel-raise-to-top"
#define GIMP_HELP_CHANNEL_LOWER                   "ammoos-channel-lower"
#define GIMP_HELP_CHANNEL_LOWER_TO_BOTTOM         "ammoos-channel-lower-to-bottom"
#define GIMP_HELP_CHANNEL_DUPLICATE               "ammoos-channel-duplicate"
#define GIMP_HELP_CHANNEL_DELETE                  "ammoos-channel-delete"
#define GIMP_HELP_CHANNEL_PREVIOUS                "ammoos-channel-previous"
#define GIMP_HELP_CHANNEL_NEXT                    "ammoos-channel-next"
#define GIMP_HELP_CHANNEL_TOP                     "ammoos-channel-top"
#define GIMP_HELP_CHANNEL_BOTTOM                  "ammoos-channel-bottom"
#define GIMP_HELP_CHANNEL_VISIBLE                 "ammoos-channel-visible"
#define GIMP_HELP_CHANNEL_LINKED                  "ammoos-channel-linked"
#define GIMP_HELP_CHANNEL_COLOR_TAG               "ammoos-channel-color-tag"
#define GIMP_HELP_CHANNEL_LOCK_PIXELS             "ammoos-channel-lock-pixels"
#define GIMP_HELP_CHANNEL_LOCK_POSITION           "ammoos-channel-lock-position"
#define GIMP_HELP_CHANNEL_LOCK_VISIBILITY         "ammoos-channel-lock-visibility"
#define GIMP_HELP_CHANNEL_SELECTION_REPLACE       "ammoos-channel-selection-replace"
#define GIMP_HELP_CHANNEL_SELECTION_ADD           "ammoos-channel-selection-add"
#define GIMP_HELP_CHANNEL_SELECTION_SUBTRACT      "ammoos-channel-selection-subtract"
#define GIMP_HELP_CHANNEL_SELECTION_INTERSECT     "ammoos-channel-selection-intersect"
#define GIMP_HELP_CHANNEL_EDIT                    "ammoos-channel-edit"

#define GIMP_HELP_QUICK_MASK                      "ammoos-quick-mask"
#define GIMP_HELP_QUICK_MASK_TOGGLE               "ammoos-quick-mask-toggle"
#define GIMP_HELP_QUICK_MASK_INVERT               "ammoos-quick-mask-invert"
#define GIMP_HELP_QUICK_MASK_EDIT                 "ammoos-quick-mask-edit"

#define GIMP_HELP_PATH_DIALOG                     "ammoos-path-dialog"
#define GIMP_HELP_PATH_NEW                        "ammoos-path-new"
#define GIMP_HELP_PATH_PREVIOUS                   "ammoos-path-previous"
#define GIMP_HELP_PATH_NEXT                       "ammoos-path-next"
#define GIMP_HELP_PATH_TOP                        "ammoos-path-top"
#define GIMP_HELP_PATH_BOTTOM                     "ammoos-path-bottom"
#define GIMP_HELP_PATH_RAISE                      "ammoos-path-raise"
#define GIMP_HELP_PATH_RAISE_TO_TOP               "ammoos-path-raise-to-top"
#define GIMP_HELP_PATH_LOWER                      "ammoos-path-lower"
#define GIMP_HELP_PATH_LOWER_TO_BOTTOM            "ammoos-path-lower-to-bottom"
#define GIMP_HELP_PATH_DUPLICATE                  "ammoos-path-duplicate"
#define GIMP_HELP_PATH_DELETE                     "ammoos-path-delete"
#define GIMP_HELP_PATH_MERGE_VISIBLE              "ammoos-path-merge-visible"
#define GIMP_HELP_PATH_VISIBLE                    "ammoos-path-visible"
#define GIMP_HELP_PATH_LINKED                     "ammoos-path-linked"
#define GIMP_HELP_PATH_COLOR_TAG                  "ammoos-path-color-tag"
#define GIMP_HELP_PATH_LOCK_STROKES               "ammoos-path-lock-strokes"
#define GIMP_HELP_PATH_LOCK_POSITION              "ammoos-path-lock-position"
#define GIMP_HELP_PATH_LOCK_VISIBILITY            "ammoos-path-lock-visibility"
#define GIMP_HELP_PATH_SELECTION_REPLACE          "ammoos-path-selection-replace"
#define GIMP_HELP_PATH_SELECTION_ADD              "ammoos-path-selection-add"
#define GIMP_HELP_PATH_SELECTION_SUBTRACT         "ammoos-path-selection-subtract"
#define GIMP_HELP_PATH_SELECTION_INTERSECT        "ammoos-path-selection-intersect"
#define GIMP_HELP_PATH_FILL                       "ammoos-path-fill"
#define GIMP_HELP_PATH_STROKE                     "ammoos-path-stroke"
#define GIMP_HELP_PATH_COPY                       "ammoos-path-copy"
#define GIMP_HELP_PATH_PASTE                      "ammoos-path-paste"
#define GIMP_HELP_PATH_IMPORT                     "ammoos-path-import"
#define GIMP_HELP_PATH_EXPORT                     "ammoos-path-export"
#define GIMP_HELP_PATH_EDIT                       "ammoos-path-edit"
#define GIMP_HELP_PATH_TO_VECTOR_LAYER            "ammoos-path-to-vector-layer"

#define GIMP_HELP_PATH_TOOL_DELETE_ANCHOR         "ammoos-path-path-tool-delete-anchor"
#define GIMP_HELP_PATH_TOOL_DELETE_SEGMENT        "ammoos-path-path-tool-delete-segment"
#define GIMP_HELP_PATH_TOOL_INSERT_ANCHOR         "ammoos-path-path-tool-insert-anchor"
#define GIMP_HELP_PATH_TOOL_REVERSE_STROKE        "ammoos-path-path-tool-reverse-stroke"
#define GIMP_HELP_PATH_TOOL_SHIFT_START           "ammoos-path-path-tool-shift-start"

#define GIMP_HELP_TEXT_TOOL_CUT                   "ammoos-text-tool-cut"
#define GIMP_HELP_TEXT_TOOL_COPY                  "ammoos-text-tool-copy"
#define GIMP_HELP_TEXT_TOOL_PASTE                 "ammoos-text-tool-paste"
#define GIMP_HELP_TEXT_TOOL_DELETE                "ammoos-text-tool-delete"
#define GIMP_HELP_TEXT_TOOL_OPEN_TEXT_FILE        "ammoos-text-tool-open-text-file"
#define GIMP_HELP_TEXT_TOOL_CLEAR                 "ammoos-text-tool-clear"
#define GIMP_HELP_TEXT_TOOL_TEXT_TO_PATH          "ammoos-text-tool-text-to-path"
#define GIMP_HELP_TEXT_TOOL_TEXT_ALONG_PATH       "ammoos-text-tool-text-along-path"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_LTR         "ammoos-text-tool-direction-ltr"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_RTL         "ammoos-text-tool-direction-rtl"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_TTB_RTL     "ammoos-text-tool-direction-ttb-rtl"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_TTB_RTL_UP  "ammoos-text-tool-direction-ttb-rtl-upright"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_TTB_LTR     "ammoos-text-tool-direction-ttb-ltr"
#define GIMP_HELP_TEXT_TOOL_DIRECTION_TTB_LTR_UP  "ammoos-text-tool-direction-ttb-ltr-upright"

#define GIMP_HELP_TOOL_AIRBRUSH                   "ammoos-tool-airbrush"
#define GIMP_HELP_TOOL_ALIGN                      "ammoos-tool-align"
#define GIMP_HELP_TOOL_BRIGHTNESS_CONTRAST        "ammoos-tool-brightness-contrast"
#define GIMP_HELP_TOOL_BUCKET_FILL                "ammoos-tool-bucket-fill"
#define GIMP_HELP_TOOL_BY_COLOR_SELECT            "ammoos-tool-by-color-select"
#define GIMP_HELP_TOOL_CAGE                       "ammoos-tool-cage"
#define GIMP_HELP_TOOL_CLONE                      "ammoos-tool-clone"
#define GIMP_HELP_TOOL_COLORIZE                   "ammoos-tool-colorize"
#define GIMP_HELP_TOOL_COLOR_BALANCE              "ammoos-tool-color-balance"
#define GIMP_HELP_TOOL_COLOR_PICKER               "ammoos-tool-color-picker"
#define GIMP_HELP_TOOL_CONVOLVE                   "ammoos-tool-convolve"
#define GIMP_HELP_TOOL_CROP                       "ammoos-tool-crop"
#define GIMP_HELP_TOOL_CURVES                     "ammoos-tool-curves"
#define GIMP_HELP_TOOL_DODGE_BURN                 "ammoos-tool-dodge-burn"
#define GIMP_HELP_TOOL_ELLIPSE_SELECT             "ammoos-tool-ellipse-select"
#define GIMP_HELP_TOOL_ERASER                     "ammoos-tool-eraser"
#define GIMP_HELP_TOOL_FLIP                       "ammoos-tool-flip"
#define GIMP_HELP_TOOL_FREE_SELECT                "ammoos-tool-free-select"
#define GIMP_HELP_TOOL_FOREGROUND_SELECT          "ammoos-tool-foreground-select"
#define GIMP_HELP_TOOL_FUZZY_SELECT               "ammoos-tool-fuzzy-select"
#define GIMP_HELP_TOOL_GEGL                       "ammoos-tool-gegl"
#define GIMP_HELP_TOOL_GRADIENT                   "ammoos-tool-gradient"
#define GIMP_HELP_TOOL_HANDLE_TRANSFORM           "ammoos-tool-handle-transform"
#define GIMP_HELP_TOOL_HEAL                       "ammoos-tool-heal"
#define GIMP_HELP_TOOL_HUE_SATURATION             "ammoos-tool-hue-saturation"
#define GIMP_HELP_TOOL_INK                        "ammoos-tool-ink"
#define GIMP_HELP_TOOL_ISCISSORS                  "ammoos-tool-iscissors"
#define GIMP_HELP_TOOL_LEVELS                     "ammoos-tool-levels"
#define GIMP_HELP_TOOL_MEASURE                    "ammoos-tool-measure"
#define GIMP_HELP_TOOL_MOVE                       "ammoos-tool-move"
#define GIMP_HELP_TOOL_MYPAINT_BRUSH              "ammoos-tool-mypaint-brush"
#define GIMP_HELP_TOOL_N_POINT_DEFORMATION        "ammoos-tool-n-point-deformation"
#define GIMP_HELP_TOOL_OFFSET                     "ammoos-tool-offset"
#define GIMP_HELP_TOOL_PATH                       "ammoos-tool-path"
#define GIMP_HELP_TOOL_PAINTBRUSH                 "ammoos-tool-paintbrush"
#define GIMP_HELP_TOOL_PENCIL                     "ammoos-tool-pencil"
#define GIMP_HELP_TOOL_PERSPECTIVE                "ammoos-tool-perspective"
#define GIMP_HELP_TOOL_PERSPECTIVE_CLONE          "ammoos-tool-perspective-clone"
#define GIMP_HELP_TOOL_RECT_SELECT                "ammoos-tool-rect-select"
#define GIMP_HELP_TOOL_ROTATE                     "ammoos-tool-rotate"
#define GIMP_HELP_TOOL_SCALE                      "ammoos-tool-scale"
#define GIMP_HELP_TOOL_SEAMLESS_CLONE             "ammoos-tool-seamless-clone"
#define GIMP_HELP_TOOL_SHEAR                      "ammoos-tool-shear"
#define GIMP_HELP_TOOL_SMUDGE                     "ammoos-tool-smudge"
#define GIMP_HELP_TOOL_TEXT                       "ammoos-tool-text"
#define GIMP_HELP_TOOL_THRESHOLD                  "ammoos-tool-threshold"
#define GIMP_HELP_TOOL_TRANSFORM_3D               "ammoos-tool-transform-3d"
#define GIMP_HELP_TOOL_UNIFIED_TRANSFORM          "ammoos-tool-unified-transform"
#define GIMP_HELP_TOOL_WARP                       "ammoos-tool-warp"
#define GIMP_HELP_TOOL_ZOOM                       "ammoos-tool-zoom"

#define GIMP_HELP_FILTER_REPEAT                   "ammoos-filter-repeat"
#define GIMP_HELP_FILTER_RESHOW                   "ammoos-filter-reshow"
#define GIMP_HELP_FILTER_RESET_ALL                "ammoos-filter-reset-all"

#define GIMP_HELP_FILTER_ALIEN_MAP                "ammoos-filter-alien-map"
#define GIMP_HELP_FILTER_ANTIALIAS                "ammoos-filter-antialias"
#define GIMP_HELP_FILTER_APPLY_CANVAS             "ammoos-filter-apply-canvas"
#define GIMP_HELP_FILTER_APPLY_LENS               "ammoos-filter-apply-lens"
#define GIMP_HELP_FILTER_BAYER_MATRIX             "ammoos-filter-bayer-matrix"
#define GIMP_HELP_FILTER_BLOOM                    "ammoos-filter-bloom"
#define GIMP_HELP_FILTER_BUMP_MAP                 "ammoos-filter-bump-map"
#define GIMP_HELP_FILTER_C2G                      "ammoos-filter-c2g"
#define GIMP_HELP_FILTER_CARTOON                  "ammoos-filter-cartoon"
#define GIMP_HELP_FILTER_CHANNEL_MIXER            "ammoos-filter-channel-mixer"
#define GIMP_HELP_FILTER_CHECKERBOARD             "ammoos-filter-checkerboard"
#define GIMP_HELP_FILTER_COLOR_ENHANCE            "ammoos-filter-color-enhance"
#define GIMP_HELP_FILTER_COLOR_EXCHANGE           "ammoos-filter-color-exchange"
#define GIMP_HELP_FILTER_COLOR_ROTATE             "ammoos-filter-color-rotate"
#define GIMP_HELP_FILTER_COLOR_TEMPERATURE        "ammoos-filter-color-temperature"
#define GIMP_HELP_FILTER_COLOR_TO_ALPHA           "ammoos-filter-color-to-alpha"
#define GIMP_HELP_FILTER_COMPONENT_EXTRACT        "ammoos-filter-component-extract"
#define GIMP_HELP_FILTER_CONVOLUTION_MATRIX       "ammoos-filter-convolution-matrix"
#define GIMP_HELP_FILTER_CUBISM                   "ammoos-filter-cubism"
#define GIMP_HELP_FILTER_DEINTERLACE              "ammoos-filter-deinterlace"
#define GIMP_HELP_FILTER_DESATURATE               "ammoos-filter-desaturate"
#define GIMP_HELP_FILTER_DIFFERENCE_OF_GAUSSIANS  "ammoos-filter-difference-of-gaussians"
#define GIMP_HELP_FILTER_DIFFRACTION_PATTERNS     "ammoos-filter-diffraction-patterns"
#define GIMP_HELP_FILTER_DILATE                   "ammoos-filter-dilate"
#define GIMP_HELP_FILTER_DISPLACE                 "ammoos-filter-displace"
#define GIMP_HELP_FILTER_DISTANCE_MAP             "ammoos-filter-distance-map"
#define GIMP_HELP_FILTER_DITHER                   "ammoos-filter-dither"
#define GIMP_HELP_FILTER_DROPSHADOW               "ammoos-filter-drop-shadow"
#define GIMP_HELP_FILTER_EDGE                     "ammoos-filter-edge"
#define GIMP_HELP_FILTER_EDGE_LAPLACE             "ammoos-filter-edge-laplace"
#define GIMP_HELP_FILTER_EDGE_NEON                "ammoos-filter-edge-neon"
#define GIMP_HELP_FILTER_EDGE_SOBEL               "ammoos-filter-edge-sobel"
#define GIMP_HELP_FILTER_EMBOSS                   "ammoos-filter-emboss"
#define GIMP_HELP_FILTER_ENGRAVE                  "ammoos-filter-engrave"
#define GIMP_HELP_FILTER_ERODE                    "ammoos-filter-erode"
#define GIMP_HELP_FILTER_EXPOSURE                 "ammoos-filter-exposure"
#define GIMP_HELP_FILTER_FATTAL_2002              "ammoos-filter-fattal-2002"
#define GIMP_HELP_FILTER_FOCUS_BLUR               "ammoos-filter-focus-blur"
#define GIMP_HELP_FILTER_FRACTAL_TRACE            "ammoos-filter-fractal-trace"
#define GIMP_HELP_FILTER_GAUSSIAN_BLUR            "ammoos-filter-gaussian-blur"
#define GIMP_HELP_FILTER_GAUSSIAN_BLUR_SELECTIVE  "ammoos-filter-gaussian-blur-selective"
#define GIMP_HELP_FILTER_GEGL_GRAPH               "ammoos-filter-gegl-graph"
#define GIMP_HELP_FILTER_GRID                     "ammoos-filter-grid"
#define GIMP_HELP_FILTER_HIGH_PASS                "ammoos-filter-high-pass"
#define GIMP_HELP_FILTER_HUE_CHROMA               "ammoos-filter-hue-chroma"
#define GIMP_HELP_FILTER_ILLUSION                 "ammoos-filter-illusion"
#define GIMP_HELP_FILTER_INVERT_LINEAR            "ammoos-filter-invert-linear"
#define GIMP_HELP_FILTER_INVERT_PERCEPTUAL        "ammoos-filter-invert-perceptual"
#define GIMP_HELP_FILTER_INVERT_VALUE             "ammoos-filter-invert-value"
#define GIMP_HELP_FILTER_IMAGE_GRADIENT           "ammoos-filter-image-gradient"
#define GIMP_HELP_FILTER_KALEIDOSCOPE             "ammoos-filter-kaleidoscope"
#define GIMP_HELP_FILTER_LENS_BLUR                "ammoos-filter-lens-blur"
#define GIMP_HELP_FILTER_LENS_DISTORTION          "ammoos-filter-lens-distortion"
#define GIMP_HELP_FILTER_LENS_FLARE               "ammoos-filter-lens-flare"
#define GIMP_HELP_FILTER_LINEAR_SINUSOID          "ammoos-filter-linear-sinusoid"
#define GIMP_HELP_FILTER_LITTLE_PLANET            "ammoos-filter-little-planet"
#define GIMP_HELP_FILTER_LONG_SHADOW              "ammoos-filter-long-shadow"
#define GIMP_HELP_FILTER_MANTIUK_2006             "ammoos-filter-mantiuk-2006"
#define GIMP_HELP_FILTER_MAZE                     "ammoos-filter-maze"
#define GIMP_HELP_FILTER_MEAN_CURVATURE_BLUR      "ammoos-filter-mean-curvature-blur"
#define GIMP_HELP_FILTER_MEDIAN_BLUR              "ammoos-filter-median-blur"
#define GIMP_HELP_FILTER_MONO_MIXER               "ammoos-filter-mono-mixer"
#define GIMP_HELP_FILTER_MOSAIC                   "ammoos-filter-mosaic"
#define GIMP_HELP_FILTER_MOTION_BLUR_CIRCULAR     "ammoos-filter-motion-blur-circular"
#define GIMP_HELP_FILTER_MOTION_BLUR_LINEAR       "ammoos-filter-motion-blur-linear"
#define GIMP_HELP_FILTER_MOTION_BLUR_ZOOM         "ammoos-filter-motion-blur-zoom"
#define GIMP_HELP_FILTER_NEWSPRINT                "ammoos-filter-newsprint"
#define GIMP_HELP_FILTER_NOISE_CELL               "ammoos-filter-noise-cell"
#define GIMP_HELP_FILTER_NOISE_CIE_LCH            "ammoos-filter-noise-cie-lch"
#define GIMP_HELP_FILTER_NOISE_HSV                "ammoos-filter-noise-hsv"
#define GIMP_HELP_FILTER_NOISE_HURL               "ammoos-filter-noise-hurl"
#define GIMP_HELP_FILTER_NOISE_PERLIN             "ammoos-filter-noise-perlin"
#define GIMP_HELP_FILTER_NOISE_PICK               "ammoos-filter-noise-pick"
#define GIMP_HELP_FILTER_NOISE_RGB                "ammoos-filter-noise-rgb"
#define GIMP_HELP_FILTER_NOISE_REDUCTION          "ammoos-filter-noise-reduction"
#define GIMP_HELP_FILTER_NOISE_SIMPLEX            "ammoos-filter-noise-simplex"
#define GIMP_HELP_FILTER_NOISE_SLUR               "ammoos-filter-noise-slur"
#define GIMP_HELP_FILTER_NOISE_SOLID              "ammoos-filter-noise-solid"
#define GIMP_HELP_FILTER_NOISE_SPREAD             "ammoos-filter-noise-spread"
#define GIMP_HELP_FILTER_NORMAL_MAP               "ammoos-filter-normal-map"
#define GIMP_HELP_FILTER_OILIFY                   "ammoos-filter-oilify"
#define GIMP_HELP_FILTER_PANORAMA_PROJECTION      "ammoos-filter-panorama-projection"
#define GIMP_HELP_FILTER_PHOTOCOPY                "ammoos-filter-photocopy"
#define GIMP_HELP_FILTER_PIXELIZE                 "ammoos-filter-pixelize"
#define GIMP_HELP_FILTER_PLASMA                   "ammoos-filter-plasma"
#define GIMP_HELP_FILTER_POLAR_COORDINATES        "ammoos-filter-polar-coordinates"
#define GIMP_HELP_FILTER_POSTERIZE                "ammoos-filter-posterize"
#define GIMP_HELP_FILTER_RECURSIVE_TRANSFORM      "ammoos-filter-recursive-transform"
#define GIMP_HELP_FILTER_RED_EYE_REMOVAL          "ammoos-filter-red-eye-removal"
#define GIMP_HELP_FILTER_REINHARD_2005            "ammoos-filter-reinhard-2005"
#define GIMP_HELP_FILTER_RGB_CLIP                 "ammoos-filter-rgb-clip"
#define GIMP_HELP_FILTER_RIPPLE                   "ammoos-filter-ripple"
#define GIMP_HELP_FILTER_SATURATION               "ammoos-filter-saturation"
#define GIMP_HELP_FILTER_SEMI_FLATTEN             "ammoos-filter-semi-flatten"
#define GIMP_HELP_FILTER_SEPIA                    "ammoos-filter-sepia"
#define GIMP_HELP_FILTER_SHADOWS_HIGHLIGHTS       "ammoos-filter-shadows-highlights"
#define GIMP_HELP_FILTER_SHIFT                    "ammoos-filter-shift"
#define GIMP_HELP_FILTER_SINUS                    "ammoos-filter-sinus"
#define GIMP_HELP_FILTER_SLIC                     "ammoos-filter-slic"
#define GIMP_HELP_FILTER_SNN_MEAN                 "ammoos-filter-snn-mean"
#define GIMP_HELP_FILTER_SOFTGLOW                 "ammoos-filter-softglow"
#define GIMP_HELP_FILTER_SPHERIZE                 "ammoos-filter-spherize"
#define GIMP_HELP_FILTER_SPIRAL                   "ammoos-filter-spiral"
#define GIMP_HELP_FILTER_STRETCH_CONTRAST         "ammoos-filter-stretch-contrast"
#define GIMP_HELP_FILTER_STRETCH_CONTRAST_HSV     "ammoos-filter-stretch-contrast-hsv"
#define GIMP_HELP_FILTER_STRESS                   "ammoos-filter-stress"
#define GIMP_HELP_FILTER_SUPERNOVA                "ammoos-filter-supernova"
#define GIMP_HELP_FILTER_THRESHOLD_ALPHA          "ammoos-filter-threshold-alpha"
#define GIMP_HELP_FILTER_TILE_GLASS               "ammoos-filter-tile-glass"
#define GIMP_HELP_FILTER_TILE_PAPER               "ammoos-filter-tile-paper"
#define GIMP_HELP_FILTER_TILE_SEAMLESS            "ammoos-filter-tile-seamless"
#define GIMP_HELP_FILTER_UNSHARP_MASK             "ammoos-filter-unsharp-mask"
#define GIMP_HELP_FILTER_VALUE_PROPAGATE          "ammoos-filter-value-propagate"
#define GIMP_HELP_FILTER_VARIABLE_BLUR            "ammoos-filter-variable-blur"
#define GIMP_HELP_FILTER_VIDEO_DEGRADATION        "ammoos-filter-video-degradation"
#define GIMP_HELP_FILTER_VIGNETTE                 "ammoos-filter-vignette"
#define GIMP_HELP_FILTER_WATERPIXELS              "ammoos-filter-waterpixels"
#define GIMP_HELP_FILTER_WAVES                    "ammoos-filter-waves"
#define GIMP_HELP_FILTER_WHIRL_PINCH              "ammoos-filter-whirl-pinch"
#define GIMP_HELP_FILTER_WIND                     "ammoos-filter-wind"

#define GIMP_HELP_TOOLBOX                         "ammoos-toolbox"
#define GIMP_HELP_TOOLBOX_COLOR_AREA              "ammoos-toolbox-color-area"
#define GIMP_HELP_TOOLBOX_IMAGE_AREA              "ammoos-toolbox-image-area"
#define GIMP_HELP_TOOLBOX_INDICATOR_AREA          "ammoos-toolbox-indicator-area"
#define GIMP_HELP_TOOLBOX_DEFAULT_COLORS          "ammoos-toolbox-default-colors"
#define GIMP_HELP_TOOLBOX_SWAP_COLORS             "ammoos-toolbox-swap-colors"
#define GIMP_HELP_TOOLBOX_SWAP_TOOLS              "ammoos-toolbox-swap-tools"

#define GIMP_HELP_BRUSH_DIALOG                    "ammoos-brush-dialog"
#define GIMP_HELP_BRUSH_EDIT                      "ammoos-brush-edit"
#define GIMP_HELP_BRUSH_OPEN_AS_IMAGE             "ammoos-brush-open-as-image"
#define GIMP_HELP_BRUSH_NEW                       "ammoos-brush-new"
#define GIMP_HELP_BRUSH_DUPLICATE                 "ammoos-brush-duplicate"
#define GIMP_HELP_BRUSH_COPY_LOCATION             "ammoos-brush-copy-location"
#define GIMP_HELP_BRUSH_SHOW_IN_FILE_MANAGER      "ammoos-brush-show-in-file-manager"
#define GIMP_HELP_BRUSH_DELETE                    "ammoos-brush-delete"
#define GIMP_HELP_BRUSH_REFRESH                   "ammoos-brush-refresh"

#define GIMP_HELP_BRUSH_EDITOR_DIALOG             "ammoos-brush-editor-dialog"
#define GIMP_HELP_BRUSH_EDITOR_EDIT_ACTIVE        "ammoos-brush-editor-edit-active"

#define GIMP_HELP_DYNAMICS_EDITOR_DIALOG          "ammoos-dynamics-editor-dialog"

#define GIMP_HELP_TOOL_PRESET_EDITOR_DIALOG       "ammoos-tool-preset-editor-dialog"
#define GIMP_HELP_TOOL_PRESET_EDITOR_EDIT_ACTIVE  "ammoos-tool-preset-editor-edit-active"

#define GIMP_HELP_DYNAMICS_DIALOG                 "ammoos-dynamics-dialog"
#define GIMP_HELP_DYNAMICS_EDIT                   "ammoos-dynamics-edit"
#define GIMP_HELP_DYNAMICS_NEW                    "ammoos-dynamics-new"
#define GIMP_HELP_DYNAMICS_DUPLICATE              "ammoos-dynamics-duplicate"
#define GIMP_HELP_DYNAMICS_COPY_LOCATION          "ammoos-dynamics-copy-location"
#define GIMP_HELP_DYNAMICS_SHOW_IN_FILE_MANAGER   "ammoos-dynamics-show-in-file-manager"
#define GIMP_HELP_DYNAMICS_DELETE                 "ammoos-dynamics-delete"
#define GIMP_HELP_DYNAMICS_REFRESH                "ammoos-dynamics-refresh"

#define GIMP_HELP_MYPAINT_BRUSH_DIALOG            "ammoos-mypaint-brush-dialog"
#define GIMP_HELP_MYPAINT_BRUSH_EDIT              "ammoos-mypaint-brush-edit"
#define GIMP_HELP_MYPAINT_BRUSH_NEW               "ammoos-mypaint-brush-new"
#define GIMP_HELP_MYPAINT_BRUSH_DUPLICATE         "ammoos-mypaint-brush-duplicate"
#define GIMP_HELP_MYPAINT_BRUSH_COPY_LOCATION     "ammoos-mypaint-brush-copy-location"
#define GIMP_HELP_MYPAINT_BRUSH_SHOW_IN_FILE_MANAGER "ammoos-mypaint-brush-show-in-file-manager"
#define GIMP_HELP_MYPAINT_BRUSH_DELETE            "ammoos-mypaint-brush-delete"
#define GIMP_HELP_MYPAINT_BRUSH_REFRESH           "ammoos-mypaint-brush-refresh"

#define GIMP_HELP_PATTERN_DIALOG                  "ammoos-pattern-dialog"
#define GIMP_HELP_PATTERN_EDIT                    "ammoos-pattern-edit"
#define GIMP_HELP_PATTERN_OPEN_AS_IMAGE           "ammoos-pattern-open-as-image"
#define GIMP_HELP_PATTERN_NEW                     "ammoos-pattern-new"
#define GIMP_HELP_PATTERN_DUPLICATE               "ammoos-pattern-duplicate"
#define GIMP_HELP_PATTERN_COPY_LOCATION           "ammoos-pattern-copy-location"
#define GIMP_HELP_PATTERN_SHOW_IN_FILE_MANAGER    "ammoos-pattern-show-in-file-manager"
#define GIMP_HELP_PATTERN_DELETE                  "ammoos-pattern-delete"
#define GIMP_HELP_PATTERN_REFRESH                 "ammoos-pattern-refresh"

#define GIMP_HELP_GRADIENT_DIALOG                 "ammoos-gradient-dialog"
#define GIMP_HELP_GRADIENT_EDIT                   "ammoos-gradient-edit"
#define GIMP_HELP_GRADIENT_NEW                    "ammoos-gradient-new"
#define GIMP_HELP_GRADIENT_DUPLICATE              "ammoos-gradient-duplicate"
#define GIMP_HELP_GRADIENT_COPY_LOCATION          "ammoos-gradient-copy-location"
#define GIMP_HELP_GRADIENT_SHOW_IN_FILE_MANAGER   "ammoos-gradient-show-in-file-manager"
#define GIMP_HELP_GRADIENT_DELETE                 "ammoos-gradient-delete"
#define GIMP_HELP_GRADIENT_REFRESH                "ammoos-gradient-refresh"
#define GIMP_HELP_GRADIENT_SAVE_AS_POV            "ammoos-gradient-save-as-pov"

#define GIMP_HELP_GRADIENT_EDITOR_DIALOG          "ammoos-gradient-editor-dialog"
#define GIMP_HELP_GRADIENT_EDITOR_LEFT_COLOR      "ammoos-gradient-editor-left-color"
#define GIMP_HELP_GRADIENT_EDITOR_LEFT_LOAD       "ammoos-gradient-editor-left-load"
#define GIMP_HELP_GRADIENT_EDITOR_LEFT_SAVE       "ammoos-gradient-editor-left-save"
#define GIMP_HELP_GRADIENT_EDITOR_RIGHT_COLOR     "ammoos-gradient-editor-right-color"
#define GIMP_HELP_GRADIENT_EDITOR_RIGHT_LOAD      "ammoos-gradient-editor-right-load"
#define GIMP_HELP_GRADIENT_EDITOR_RIGHT_SAVE      "ammoos-gradient-editor-right-save"
#define GIMP_HELP_GRADIENT_EDITOR_BLENDING        "ammoos-gradient-editor-blending"
#define GIMP_HELP_GRADIENT_EDITOR_COLORING        "ammoos-gradient-editor-coloring"
#define GIMP_HELP_GRADIENT_EDITOR_FLIP            "ammoos-gradient-editor-flip"
#define GIMP_HELP_GRADIENT_EDITOR_REPLICATE       "ammoos-gradient-editor-replicate"
#define GIMP_HELP_GRADIENT_EDITOR_SPLIT_MIDPOINT  "ammoos-gradient-editor-split-midpoint"
#define GIMP_HELP_GRADIENT_EDITOR_SPLIT_UNIFORM   "ammoos-gradient-editor-split-uniform"
#define GIMP_HELP_GRADIENT_EDITOR_DELETE          "ammoos-gradient-editor-delete"
#define GIMP_HELP_GRADIENT_EDITOR_RECENTER        "ammoos-gradient-editor-recenter"
#define GIMP_HELP_GRADIENT_EDITOR_REDISTRIBUTE    "ammoos-gradient-editor-redistribute"
#define GIMP_HELP_GRADIENT_EDITOR_BLEND_COLOR     "ammoos-gradient-editor-blend-color"
#define GIMP_HELP_GRADIENT_EDITOR_BLEND_OPACITY   "ammoos-gradient-editor-blend-opacity"
#define GIMP_HELP_GRADIENT_EDITOR_ZOOM_OUT        "ammoos-gradient-editor-zoom-out"
#define GIMP_HELP_GRADIENT_EDITOR_ZOOM_IN         "ammoos-gradient-editor-zoom-in"
#define GIMP_HELP_GRADIENT_EDITOR_ZOOM_ALL        "ammoos-gradient-editor-zoom-all"
#define GIMP_HELP_GRADIENT_EDITOR_EDIT_ACTIVE     "ammoos-gradient-editor-edit-active"

#define GIMP_HELP_PALETTE_DIALOG                  "ammoos-palette-dialog"
#define GIMP_HELP_PALETTE_EDIT                    "ammoos-palette-edit"
#define GIMP_HELP_PALETTE_NEW                     "ammoos-palette-new"
#define GIMP_HELP_PALETTE_DUPLICATE               "ammoos-palette-duplicate"
#define GIMP_HELP_PALETTE_COPY_LOCATION           "ammoos-palette-copy-location"
#define GIMP_HELP_PALETTE_SHOW_IN_FILE_MANAGER    "ammoos-palette-show-in-file-manager"
#define GIMP_HELP_PALETTE_DELETE                  "ammoos-palette-delete"
#define GIMP_HELP_PALETTE_REFRESH                 "ammoos-palette-refresh"
#define GIMP_HELP_PALETTE_IMPORT                  "ammoos-palette-import"
#define GIMP_HELP_PALETTE_MERGE                   "ammoos-palette-merge"

#define GIMP_HELP_PALETTE_EDITOR_DIALOG           "ammoos-palette-editor-dialog"
#define GIMP_HELP_PALETTE_EDITOR_NEW              "ammoos-palette-editor-new"
#define GIMP_HELP_PALETTE_EDITOR_EDIT             "ammoos-palette-editor-edit"
#define GIMP_HELP_PALETTE_EDITOR_DELETE           "ammoos-palette-editor-delete"
#define GIMP_HELP_PALETTE_EDITOR_ZOOM_OUT         "ammoos-palette-editor-zoom-out"
#define GIMP_HELP_PALETTE_EDITOR_ZOOM_IN          "ammoos-palette-editor-zoom-in"
#define GIMP_HELP_PALETTE_EDITOR_ZOOM_ALL         "ammoos-palette-editor-zoom-all"
#define GIMP_HELP_PALETTE_EDITOR_EDIT_ACTIVE      "ammoos-palette-editor-edit-active"

#define GIMP_HELP_FONT_DIALOG                     "ammoos-font-dialog"
#define GIMP_HELP_FONT_REFRESH                    "ammoos-font-refresh"

#define GIMP_HELP_BUFFER_DIALOG                   "ammoos-buffer-dialog"
#define GIMP_HELP_BUFFER_CUT                      "ammoos-buffer-cut"
#define GIMP_HELP_BUFFER_COPY                     "ammoos-buffer-copy"
#define GIMP_HELP_BUFFER_PASTE                    "ammoos-buffer-paste"
#define GIMP_HELP_BUFFER_PASTE_IN_PLACE           "ammoos-buffer-paste-in-place"
#define GIMP_HELP_BUFFER_PASTE_INTO               "ammoos-buffer-paste-into"
#define GIMP_HELP_BUFFER_PASTE_INTO_IN_PLACE      "ammoos-buffer-paste-into-in-place"
#define GIMP_HELP_BUFFER_PASTE_AS_NEW_LAYER       "ammoos-buffer-paste-as-new-layer"
#define GIMP_HELP_BUFFER_PASTE_AS_NEW_LAYER_IN_PLACE "ammoos-buffer-paste-as-new-layer-in-place"
#define GIMP_HELP_BUFFER_PASTE_AS_NEW_IMAGE       "ammoos-buffer-paste-as-new-image"
#define GIMP_HELP_BUFFER_DELETE                   "ammoos-buffer-delete"

#define GIMP_HELP_TOOL_PRESET_DIALOG              "ammoos-tool-preset-dialog"
#define GIMP_HELP_TOOL_PRESET_EDIT                "ammoos-tool-preset-edit"
#define GIMP_HELP_TOOL_PRESET_NEW                 "ammoos-tool-preset-new"
#define GIMP_HELP_TOOL_PRESET_DUPLICATE           "ammoos-tool-preset-duplicate"
#define GIMP_HELP_TOOL_PRESET_COPY_LOCATION       "ammoos-tool-preset-copy-location"
#define GIMP_HELP_TOOL_PRESET_SHOW_IN_FILE_MANAGER "ammoos-tool-preset-show-in-file-manager"
#define GIMP_HELP_TOOL_PRESET_SAVE                "ammoos-tool-preset-save"
#define GIMP_HELP_TOOL_PRESET_RESTORE             "ammoos-tool-preset-restore"
#define GIMP_HELP_TOOL_PRESET_DELETE              "ammoos-tool-preset-delete"
#define GIMP_HELP_TOOL_PRESET_REFRESH             "ammoos-tool-preset-refresh"

#define GIMP_HELP_DOCUMENT_CLEAR                  "ammoos-document-clear"
#define GIMP_HELP_DOCUMENT_COPY_LOCATION          "ammoos-document-copy-location"
#define GIMP_HELP_DOCUMENT_SHOW_IN_FILE_MANAGER   "ammoos-document-show-in-file-manager"
#define GIMP_HELP_DOCUMENT_DIALOG                 "ammoos-document-dialog"
#define GIMP_HELP_DOCUMENT_OPEN                   "ammoos-document-open"
#define GIMP_HELP_DOCUMENT_REMOVE                 "ammoos-document-remove"
#define GIMP_HELP_DOCUMENT_REFRESH                "ammoos-document-refresh"

#define GIMP_HELP_TEMPLATE_DIALOG                 "ammoos-template-dialog"
#define GIMP_HELP_TEMPLATE_NEW                    "ammoos-template-new"
#define GIMP_HELP_TEMPLATE_DUPLICATE              "ammoos-template-duplicate"
#define GIMP_HELP_TEMPLATE_EDIT                   "ammoos-template-edit"
#define GIMP_HELP_TEMPLATE_IMAGE_NEW              "ammoos-template-image-new"
#define GIMP_HELP_TEMPLATE_DELETE                 "ammoos-template-delete"

#define GIMP_HELP_TOOL_OPTIONS_DIALOG             "ammoos-tool-options-dialog"
#define GIMP_HELP_TOOL_OPTIONS_SAVE               "ammoos-tool-options-save"
#define GIMP_HELP_TOOL_OPTIONS_RESTORE            "ammoos-tool-options-restore"
#define GIMP_HELP_TOOL_OPTIONS_EDIT               "ammoos-tool-options-edit"
#define GIMP_HELP_TOOL_OPTIONS_DELETE             "ammoos-tool-options-delete"
#define GIMP_HELP_TOOL_OPTIONS_RESET              "ammoos-tool-options-reset"

#define GIMP_HELP_ERRORS_DIALOG                   "ammoos-errors-dialog"
#define GIMP_HELP_ERRORS_HIGHLIGHT                "ammoos-errors-highlight"
#define GIMP_HELP_ERRORS_CLEAR                    "ammoos-errors-clear"
#define GIMP_HELP_ERRORS_SAVE                     "ammoos-errors-save"
#define GIMP_HELP_ERRORS_SELECT_ALL               "ammoos-errors-select-all"

#define GIMP_HELP_PREFS_DIALOG                    "ammoos-prefs-dialog"
#define GIMP_HELP_PREFS_SYSTEM_RESOURCES          "ammoos-prefs-system-resources"
#define GIMP_HELP_PREFS_DEBUGGING                 "ammoos-prefs-debugging"
#define GIMP_HELP_PREFS_COLOR_MANAGEMENT          "ammoos-prefs-color-management"
#define GIMP_HELP_PREFS_IMPORT_EXPORT             "ammoos-prefs-import-export"
#define GIMP_HELP_PREFS_PLAYGROUND                "ammoos-prefs-playground"
#define GIMP_HELP_PREFS_TOOL_OPTIONS              "ammoos-prefs-tool-options"
#define GIMP_HELP_PREFS_NEW_IMAGE                 "ammoos-prefs-new-image"
#define GIMP_HELP_PREFS_DEFAULT_GRID              "ammoos-prefs-default-grid"
#define GIMP_HELP_PREFS_INTERFACE                 "ammoos-prefs-interface"
#define GIMP_HELP_PREFS_THEME                     "ammoos-prefs-theme"
#define GIMP_HELP_PREFS_ICON_THEME                "ammoos-prefs-icon-theme"
#define GIMP_HELP_PREFS_TOOLBOX                   "ammoos-prefs-toolbox"
#define GIMP_HELP_PREFS_DIALOG_DEFAULTS           "ammoos-prefs-dialog-defaults"
#define GIMP_HELP_PREFS_HELP                      "ammoos-prefs-help"
#define GIMP_HELP_PREFS_DISPLAY                   "ammoos-prefs-display"
#define GIMP_HELP_PREFS_WINDOW_MANAGEMENT         "ammoos-prefs-window-management"
#define GIMP_HELP_PREFS_CANVAS_INTERACTION        "ammoos-prefs-canvas-interaction"
#define GIMP_HELP_PREFS_CANVAS_MODIFIERS          "ammoos-prefs-canvas-modifiers"
#define GIMP_HELP_PREFS_IMAGE_WINDOW              "ammoos-prefs-image-window"
#define GIMP_HELP_PREFS_IMAGE_WINDOW_APPEARANCE   "ammoos-prefs-image-window-appearance"
#define GIMP_HELP_PREFS_IMAGE_WINDOW_TITLE        "ammoos-prefs-image-window-title"
#define GIMP_HELP_PREFS_IMAGE_WINDOW_SNAPPING     "ammoos-prefs-image-window-snapping"
#define GIMP_HELP_PREFS_INPUT_DEVICES             "ammoos-prefs-input-devices"
#define GIMP_HELP_PREFS_INPUT_CONTROLLERS         "ammoos-prefs-input-controllers"
#define GIMP_HELP_PREFS_FOLDERS                   "ammoos-prefs-folders"
#define GIMP_HELP_PREFS_FOLDERS_BRUSHES           "ammoos-prefs-folders-brushes"
#define GIMP_HELP_PREFS_FOLDERS_DYNAMICS          "ammoos-prefs-folders-dynamics"
#define GIMP_HELP_PREFS_FOLDERS_PATTERNS          "ammoos-prefs-folders-patterns"
#define GIMP_HELP_PREFS_FOLDERS_PALETTES          "ammoos-prefs-folders-palettes"
#define GIMP_HELP_PREFS_FOLDERS_GRADIENTS         "ammoos-prefs-folders-gradients"
#define GIMP_HELP_PREFS_FOLDERS_FONTS             "ammoos-prefs-folders-fonts"
#define GIMP_HELP_PREFS_FOLDERS_TOOL_PRESETS      "ammoos-prefs-folders-tool-presets"
#define GIMP_HELP_PREFS_FOLDERS_MYPAINT_BRUSHES   "ammoos-prefs-folders-mypaint-brushes"
#define GIMP_HELP_PREFS_FOLDERS_PLUG_INS          "ammoos-prefs-folders-plug-ins"
#define GIMP_HELP_PREFS_FOLDERS_SCRIPTS           "ammoos-prefs-folders-scripts"
#define GIMP_HELP_PREFS_FOLDERS_MODULES           "ammoos-prefs-folders-modules"
#define GIMP_HELP_PREFS_FOLDERS_INTERPRETERS      "ammoos-prefs-folders-interpreters"
#define GIMP_HELP_PREFS_FOLDERS_ENVIRONMENT       "ammoos-prefs-folders-environment"
#define GIMP_HELP_PREFS_FOLDERS_THEMES            "ammoos-prefs-folders-themes"
#define GIMP_HELP_PREFS_FOLDERS_ICON_THEMES       "ammoos-prefs-folders-icon-themes"

#define GIMP_HELP_INPUT_DEVICES                   "ammoos-help-input-devices"
#define GIMP_HELP_KEYBOARD_SHORTCUTS              "ammoos-help-keyboard-shortcuts"

#define GIMP_HELP_INDEXED_PALETTE_DIALOG          "ammoos-indexed-palette-dialog"
#define GIMP_HELP_INDEXED_PALETTE_EDIT            "ammoos-indexed-palette-edit"
#define GIMP_HELP_INDEXED_PALETTE_ADD             "ammoos-indexed-palette-add"
#define GIMP_HELP_INDEXED_PALETTE_SELECTION_REPLACE "ammoos-indexed-palette-selection-replace"
#define GIMP_HELP_INDEXED_PALETTE_SELECTION_ADD   "ammoos-indexed-palette-selection-add"
#define GIMP_HELP_INDEXED_PALETTE_SELECTION_SUBTRACT "ammoos-indexed-palette-selection-subtract"
#define GIMP_HELP_INDEXED_PALETTE_SELECTION_INTERSECT "ammoos-indexed-palette-selection-intersect"

#define GIMP_HELP_POINTER_INFO_DIALOG             "ammoos-pointer-info-dialog"
#define GIMP_HELP_POINTER_INFO_SAMPLE_MERGED      "ammoos-pointer-info-sample-merged"

#define GIMP_HELP_SAMPLE_POINT_DIALOG             "ammoos-sample-point-dialog"
#define GIMP_HELP_SAMPLE_POINT_SAMPLE_MERGED      "ammoos-sample-point-sample-merged"

#define GIMP_HELP_DASHBOARD_DIALOG                "ammoos-dashboard-dialog"
#define GIMP_HELP_DASHBOARD_GROUPS                "ammoos-dashboard-groups"
#define GIMP_HELP_DASHBOARD_UPDATE_INTERVAL       "ammoos-dashboard-update-interval"
#define GIMP_HELP_DASHBOARD_HISTORY_DURATION      "ammoos-dashboard-history-duration"
#define GIMP_HELP_DASHBOARD_LOG_RECORD            "ammoos-dashboard-log-record"
#define GIMP_HELP_DASHBOARD_LOG_ADD_MARKER        "ammoos-dashboard-log-add-marker"
#define GIMP_HELP_DASHBOARD_LOG_ADD_EMPTY_MARKER  "ammoos-dashboard-log-add-empty-marker"
#define GIMP_HELP_DASHBOARD_RESET                 "ammoos-dashboard-reset"
#define GIMP_HELP_DASHBOARD_LOW_SWAP_SPACE_WARNING "ammoos-dashboard-low-swap-space-warning"

#define GIMP_HELP_DOCK                            "ammoos-dock"
#define GIMP_HELP_DOCK_CLOSE                      "ammoos-dock-close"
#define GIMP_HELP_DOCK_IMAGE_MENU                 "ammoos-dock-image-menu"
#define GIMP_HELP_DOCK_AUTO_BUTTON                "ammoos-dock-auto-button"
#define GIMP_HELP_DOCK_CHANGE_SCREEN              "ammoos-dock-change-screen"

#define GIMP_HELP_DOCK_TAB_ADD                    "ammoos-dock-tab-add"
#define GIMP_HELP_DOCK_TAB_CLOSE                  "ammoos-dock-tab-close"
#define GIMP_HELP_DOCK_TAB_LOCK                   "ammoos-dock-tab-lock"
#define GIMP_HELP_DOCK_TAB_MENU                   "ammoos-dock-tab-menu"
#define GIMP_HELP_DOCK_TAB_DETACH                 "ammoos-dock-tab-detach"
#define GIMP_HELP_DOCK_PREVIEW_SIZE               "ammoos-dock-preview-size"
#define GIMP_HELP_DOCK_TAB_STYLE                  "ammoos-dock-tab-style"
#define GIMP_HELP_DOCK_VIEW_AS_LIST               "ammoos-dock-view-as-list"
#define GIMP_HELP_DOCK_VIEW_AS_GRID               "ammoos-dock-view-as-grid"
#define GIMP_HELP_DOCK_SHOW_BUTTON_BAR            "ammoos-dock-show-button-bar"

#define GIMP_HELP_ABOUT_DIALOG                    "ammoos-about-dialog"
#define GIMP_HELP_ACTION_SEARCH_DIALOG            "ammoos-action-search-dialog"
#define GIMP_HELP_COLOR_DIALOG                    "ammoos-color-dialog"
#define GIMP_HELP_DEVICE_STATUS_DIALOG            "ammoos-device-status-dialog"
#define GIMP_HELP_DISPLAY_FILTER_DIALOG           "ammoos-display-filter-dialog"
#define GIMP_HELP_HISTOGRAM_DIALOG                "ammoos-histogram-dialog"
#define GIMP_HELP_MODULE_DIALOG                   "ammoos-module-dialog"
#define GIMP_HELP_NAVIGATION_DIALOG               "ammoos-navigation-dialog"
#define GIMP_HELP_SYMMETRY_DIALOG                 "ammoos-symmetry-dialog"
#define GIMP_HELP_TEXT_EDITOR_DIALOG              "ammoos-text-editor-dialog"
#define GIMP_HELP_TIPS_DIALOG                     "ammoos-tips-dialog"
#define GIMP_HELP_UNDO_DIALOG                     "ammoos-undo-dialog"
#define GIMP_HELP_WELCOME_DIALOG                  "ammoos-welcome-dialog"

#define GIMP_HELP_EXPORT_DIALOG                   "ammoos-export-dialog"
#define GIMP_HELP_EXPORT_CONFIRM_DIALOG           "ammoos-export-confirm-dialog"

#define GIMP_HELP_WINDOWS_SHOW_DOCK               "ammoos-windows-show-dock"
#define GIMP_HELP_WINDOWS_HIDE_DOCKS              "ammoos-windows-hide-docks"
#define GIMP_HELP_WINDOWS_SHOW_TABS               "ammoos-windows-show-tabs"
#define GIMP_HELP_WINDOWS_TABS_POSITION           "ammoos-windows-tabs-position"
#define GIMP_HELP_WINDOWS_USE_SINGLE_WINDOW_MODE  "ammoos-windows-use-single-window-mode"
#define GIMP_HELP_WINDOWS_OPEN_RECENT_DOCK        "ammoos-windows-open-recent-dock"

#define GIMP_HELP_HELP                            "ammoos-help"
#define GIMP_HELP_HELP_CONTEXT                    "ammoos-help-context"

/* Most of the colordisplay, colorselector and controller id's below are not
   used since they are needed in /libgimpwidgets/ or /modules/ where this can't
   be used. Instead the strings are used there directly.
   We define them here anyway, to make ammoos-help aware of them.
 */
#define GIMP_HELP_COLORDISPLAY_ACES_RRT           "ammoos-colordisplay-aces-rrt"
#define GIMP_HELP_COLORDISPLAY_CLIP               "ammoos-colordisplay-clip"
#define GIMP_HELP_COLORDISPLAY_COLORBLIND         "ammoos-colordisplay-colorblind"
#define GIMP_HELP_COLORDISPLAY_CONTRAST           "ammoos-colordisplay-contrast"
#define GIMP_HELP_COLORDISPLAY_GAMMA              "ammoos-colordisplay-gamma"

#define GIMP_HELP_COLORSELECTOR_CMYK              "ammoos-colorselector-cmyk"
#define GIMP_HELP_COLORSELECTOR_GIMP              "ammoos-colorselector-ammoos"
#define GIMP_HELP_COLORSELECTOR_NOTEBOOK          "ammoos-colorselector-notebook"
#define GIMP_HELP_COLORSELECTOR_PALETTE           "ammoos-colorselector-palette"
#define GIMP_HELP_COLORSELECTOR_SCALES            "ammoos-colorselector-scales"
#define GIMP_HELP_COLORSELECTOR_TRIANGLE          "ammoos-colorselector-triangle"
#define GIMP_HELP_COLORSELECTOR_WATERCOLOR        "ammoos-colorselector-watercolor"

#define GIMP_HELP_CONTROLLER_KEYBOARD             "ammoos-controller-keyboard"
#define GIMP_HELP_CONTROLLER_DIRECTX_DIRECTINPUT  "ammoos-controller-directx-directinput"
#define GIMP_HELP_CONTROLLER_LINUX_INPUT          "ammoos-controller-linux-input"
#define GIMP_HELP_CONTROLLER_MIDI                 "ammoos-controller-midi"
#define GIMP_HELP_CONTROLLER_WHEEL                "ammoos-controller-wheel"

#define GIMP_HELP_EXTENSIONS_DIALOG               "ammoos-extensions-dialog"
#define GIMP_HELP_EXTENSIONS_INSTALLED            "ammoos-extensions-installed"
#define GIMP_HELP_EXTENSIONS_SYSTEM               "ammoos-extensions-system"
#define GIMP_HELP_EXTENSIONS_INSTALL              "ammoos-extensions-install"
