# NEXUS firmware threat hardening 2026-07-02T14:50:37Z
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
kernel.yama.ptrace_scope = 2
kernel.perf_event_paranoid = 3
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
