# NEXUS firmware threat blacklist 2026-07-02T14:50:37Z
blacklist msr
install msr /bin/false
blacklist acpi_custom_method
install acpi_custom_method /bin/false
blacklist cpuid
install cpuid /bin/false
